project:
  type: website
  output-dir: docs

website:
  title: "Jabber Jazz | Content Notes"
  description: "Notes from podcast episodes and video series published by Jabber Jazz"
  navbar:
    right:
      - icon: twitter
        href: https://twitter.com
      - icon: youtube
        href: https://www.youtube.com/jabberjazz
format:
  html:
    theme: theme.scss



